include: package:lints/recommended.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  exclude:
    - 'example/**'

linter:
  rules:
    - public_member_api_docs
    - always_declare_return_types
    - unawaited_futures
